name: IO-All-LWP
version: 0.10
abstract: Use HTTP and FTP URLs with IO::All
author: Ivan Tubert-Brohman <itub@cpan.org>
license: perl
distribution_type: module
requires:
  perl: 5.8.0
  IO::All: 0.30
  LWP: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.33
